# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "flowermate.xcodeproj")
    get_provisioning_profile
    build_app(workspace: "flowermate.xcworkspace", scheme: "flowermate")
    upload_to_testflight(
    username: "ronghv8@163.com",
    distribute_external: true,
    notify_external_testers: true,
    groups:"外部测试",
    changelog:"第一版测试",
    )    
  end
end